### ISSUE TITLE
Please remove unnecessary files

### ISSUE THREAD

**Issue by pcav** [fernando1980/viewAttributes#3]
.pyc etc.
They are generated automatically during installation.
Thanks.

**Comment by fernando1980** [comment]
Ok, I'll need help. Which are the necessary files? Is there any place where I can read about it?
Thanks.

**Comment by pcav** [comment]
Please check the general instructions:
http://plugins.qgis.org/
Thanks.

**Comment by fernando1980** [comment]
Well, I've just deleted unnecessary files (github and qgis repository). I've read the general instructions and I think that all is OK. Please, check it out and tell me if I've done well.
Thanks.
